### ISSUE TITLE
Markdown tables

### ISSUE THREAD

**Issue by tdannecy** [pioul/Minimalist-Markdown-Editor-for-Chrome#2]
At the moment, there's no support for tables in markdown in the editor. This isn't rendering correctly:
<code>|   |   |</code>
<code>|---|---|</code>

**Comment by pioul** [comment]
And now it is :-) [v3.1.0](https://github.com/pioul/Minimalist-Online-Markdown-Editor/releases/tag/v3.1.0) comes with a new Markdown converter that's faster and supports additional stuff, including GFM tables. The web app and Chrome app have been updated already, so feel free to give tables a try!
