### ISSUE TITLE
Increase font size

### ISSUE THREAD

**Issue by orschiro** [pioul/Minimalist-Markdown-Editor-for-Chrome#8]
And finally, 

Personally I find the font size very small. Is there any possibility to let the user increase the font size?

Thankfully,

Robert

**Comment by pioul** [comment]
Hey, thanks for the great idea!

I released this feature back in July following your suggestion and others'! It's available in the Settings panel, where you can also see the shortcuts for changing the text size. Sorry for following up only now, hopefully you were able to stumble on the feature in the meantime! :)

Thanks again for the help!

**Comment by orschiro** [comment]
Dear @pioul, 

I could increase the font size successfully. Great writing experience. 

Thank you!

Robert
